-- ----------------------------
-- Table structure for "C##FHBOOT"."BUS_PUBLICMETER"
-- ----------------------------
-- DROP TABLE "C##FHBOOT"."BUS_PUBLICMETER";
CREATE TABLE "C##FHBOOT"."BUS_PUBLICMETER" (
	"PRECINCT_ID" VARCHAR2(255 BYTE) NULL ,
	"NAME" VARCHAR2(255 BYTE) NULL ,
	"CODE" VARCHAR2(255 BYTE) NULL ,
	"DESCR" VARCHAR2(255 BYTE) NULL ,
	"ISDELETE" NUMBER(1) NULL ,
	"CREATOR" VARCHAR2(255 BYTE) NULL ,
	"CREATTIME" VARCHAR2(32 BYTE) NULL ,
	"OPERATOR" VARCHAR2(255 BYTE) NULL ,
	"OPERATTIME" VARCHAR2(32 BYTE) NULL ,
	"TYPE" NUMBER(1) NULL ,
	"METERINDEX" VARCHAR2(255 BYTE) NULL ,
	"CYCLE" NUMBER(1) NULL ,
	"PUBLICMETER_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."PRECINCT_ID" IS '管理区';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."NAME" IS '巡更点名称';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."CODE" IS '编号';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."DESCR" IS '备注';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."ISDELETE" IS '是否删除';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."CREATOR" IS '创建人';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."CREATTIME" IS '创建时间';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."OPERATOR" IS '操作人';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."OPERATTIME" IS '操作时间';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."TYPE" IS '仪表类型';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."METERINDEX" IS '仪表指数';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."CYCLE" IS '抄表周期';
COMMENT ON COLUMN "C##FHBOOT"."BUS_PUBLICMETER"."PUBLICMETER_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table BUS_PUBLICMETER
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHBOOT"."BUS_PUBLICMETER"

-- ----------------------------

ALTER TABLE "C##FHBOOT"."BUS_PUBLICMETER" ADD CHECK ("PUBLICMETER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHBOOT"."BUS_PUBLICMETER"
-- ----------------------------
ALTER TABLE "C##FHBOOT"."BUS_PUBLICMETER" ADD PRIMARY KEY ("PUBLICMETER_ID");
