-- ----------------------------
-- Table structure for "C##FHBOOT"."BUS_GOODSINFO"
-- ----------------------------
-- DROP TABLE "C##FHBOOT"."BUS_GOODSINFO";
CREATE TABLE "C##FHBOOT"."BUS_GOODSINFO" (
	"GOODSNAME" VARCHAR2(255 BYTE) NULL ,
	"GOODSTYPE" VARCHAR2(255 BYTE) NULL ,
	"GOODSAMOUNT" VARCHAR2(255 BYTE) NULL ,
	"AMOUNTACTIVITY" VARCHAR2(255 BYTE) NULL ,
	"GOODSCONTENT" VARCHAR2(255 BYTE) NULL ,
	"GOODSIMG" VARCHAR2(255 BYTE) NULL ,
	"AFTERSERVICE" VARCHAR2(255 BYTE) NULL ,
	"SERVICEGUARANTEE" VARCHAR2(255 BYTE) NULL ,
	"HOTLINE" VARCHAR2(255 BYTE) NULL ,
	"ORDERINGINFORMATION" VARCHAR2(255 BYTE) NULL ,
	"GOODSDETAILS" VARCHAR2(255 BYTE) NULL ,
	"ISUPPERSHELF" VARCHAR2(255 BYTE) NULL ,
	"GOODSSYNOPSIS" VARCHAR2(255 BYTE) NULL ,
	"QUANTITYSOLD" VARCHAR2(255 BYTE) NULL ,
	"ISSHOW" VARCHAR2(255 BYTE) NULL ,
	"SERVICESTATEMENT" VARCHAR2(255 BYTE) NULL ,
	"INVENTORYQUANTITY" VARCHAR2(255 BYTE) NULL ,
	"ISDELETE" VARCHAR2(255 BYTE) NULL ,
	"OPUSER" VARCHAR2(255 BYTE) NULL ,
	"OPDATE" VARCHAR2(32 BYTE) NULL ,
	"GOODSINFO_ID" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;

COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSNAME" IS '商品名称';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSTYPE" IS '商品类型';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSAMOUNT" IS '商品金额';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."AMOUNTACTIVITY" IS '活动金额';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSCONTENT" IS '内容';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSIMG" IS '商品图片';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."AFTERSERVICE" IS '售后服务';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."SERVICEGUARANTEE" IS '服务保障';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."HOTLINE" IS '服务热线';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."ORDERINGINFORMATION" IS '订购须知';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSDETAILS" IS '商品详情';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."ISUPPERSHELF" IS '是否上架1，是2，否';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSSYNOPSIS" IS '商品简介';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."QUANTITYSOLD" IS '已售数量';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."ISSHOW" IS '是否首页展示';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."SERVICESTATEMENT" IS '服务声明';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."INVENTORYQUANTITY" IS '库存数量';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."ISDELETE" IS '是否删除';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."OPUSER" IS '操作人';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."OPDATE" IS '操作日期';
COMMENT ON COLUMN "C##FHBOOT"."BUS_GOODSINFO"."GOODSINFO_ID" IS 'ID';

-- ----------------------------
-- Indexes structure for table BUS_GOODSINFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table "C##FHBOOT"."BUS_GOODSINFO"

-- ----------------------------

ALTER TABLE "C##FHBOOT"."BUS_GOODSINFO" ADD CHECK ("GOODSINFO_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "C##FHBOOT"."BUS_GOODSINFO"
-- ----------------------------
ALTER TABLE "C##FHBOOT"."BUS_GOODSINFO" ADD PRIMARY KEY ("GOODSINFO_ID");
