GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE BUS_GOODSINFO (
 		GOODSINFO_ID  nvarchar(100) NOT NULL,
		GOODSNAME nvarchar(255) DEFAULT NULL,
		GOODSTYPE nvarchar(255) DEFAULT NULL,
		GOODSAMOUNT nvarchar(255) DEFAULT NULL,
		AMOUNTACTIVITY nvarchar(255) DEFAULT NULL,
		GOODSCONTENT nvarchar(255) DEFAULT NULL,
		GOODSIMG nvarchar(255) DEFAULT NULL,
		AFTERSERVICE nvarchar(255) DEFAULT NULL,
		SERVICEGUARANTEE nvarchar(255) DEFAULT NULL,
		HOTLINE nvarchar(255) DEFAULT NULL,
		ORDERINGINFORMATION nvarchar(255) DEFAULT NULL,
		GOODSDETAILS nvarchar(255) DEFAULT NULL,
		ISUPPERSHELF nvarchar(255) DEFAULT NULL,
		GOODSSYNOPSIS nvarchar(255) DEFAULT NULL,
		QUANTITYSOLD nvarchar(255) DEFAULT NULL,
		ISSHOW nvarchar(255) DEFAULT NULL,
		SERVICESTATEMENT nvarchar(255) DEFAULT NULL,
		INVENTORYQUANTITY nvarchar(255) DEFAULT NULL,
		ISDELETE nvarchar(255) DEFAULT NULL,
		OPUSER nvarchar(255) DEFAULT NULL,
		OPDATE nvarchar(32) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[GOODSINFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
