GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE BUS_PUBLICMETER (
 		PUBLICMETER_ID  nvarchar(100) NOT NULL,
		PRECINCT_ID nvarchar(255) DEFAULT NULL,
		NAME nvarchar(255) DEFAULT NULL,
		CODE nvarchar(255) DEFAULT NULL,
		DESCR nvarchar(255) DEFAULT NULL,
		ISDELETE int NOT NULL,
		CREATOR nvarchar(255) DEFAULT NULL,
		CREATTIME nvarchar(32) DEFAULT NULL,
		OPERATOR nvarchar(255) DEFAULT NULL,
		OPERATTIME nvarchar(32) DEFAULT NULL,
		TYPE int NOT NULL,
		METERINDEX nvarchar(255) DEFAULT NULL,
		CYCLE int NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PUBLICMETER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
