GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE BUS_BROWSELOG (
 		BROWSELOG_ID  nvarchar(100) NOT NULL,
		PAGENAME nvarchar(255) DEFAULT NULL,
		PAGETYPE nvarchar(255) DEFAULT NULL,
		OPDATE nvarchar(255) DEFAULT NULL,
		OPUSER nvarchar(255) DEFAULT NULL,
		ISDELETE nvarchar(255) DEFAULT NULL,
		PAGEID nvarchar(255) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[BROWSELOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
